# Generated by Django 3.2.4 on 2022-05-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelos',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
    ]
